export const paper = {
  title: "HIVE-3D: Hierarchical Voxel Enhancement for High-Quality 3D Scene Generation",
  venue: "ICML 2026",
  authors: ["Bin Zang*", "Wenting Zheng*", "Xiaoliang Luo", "Zhiyuan Fang", "Shi Li", "Lvchun Wang", "Wei Yu", "Yi Zhao", "Tian Xie", "Yuchi Huo", "Rengan Xie"],
  affiliations: ["State Key Laboratory of CAD&CG, Zhejiang University", "China Mobile (Jiangxi) Virtual Reality Technology Co., Ltd."],
  abstract: "Recently, a line of works can generate impressive 3D objects from a single image, but they are limited by restricted representation resolution, making them unsuitable for 3D scene generation. We introduce HIVE-3D, a novel method for high-quality 3D scene generation based on a hierarchical voxel enhancement framework. Given a single scene image, HIVE-3D first produces a coarse initial scene, aligns hierarchical 2D image components with 3D scene components, and organizes them into a component tree. A voxel super-resolution model then refines each target instance while maintaining consistency with its coarse voxels. Coarse-to-fine enhancement of images and voxels produces high-resolution, high-quality 3D scenes and achieves state-of-the-art performance.",
  stages: [
    { number: "01", title: "2D-to-3D Scene Tree Construction", text: "Align hierarchical 2D image components with the initial 3D scene and organize the matched components into a tree." },
    { number: "02", title: "Voxel Super-Resolution", text: "Refine each target instance with its fine image crop and coarse voxels, preserving structure while recovering detail." },
    { number: "03", title: "Hierarchical Scene Generation", text: "Enhance the scene from root to leaves, then register the refined components back into one coherent 3D scene." },
  ],
  geometryMetrics: { CD: "0.0035", fScore: "84.34", iou: "0.7449" },
  imageMetrics: { SSIM: "0.79", PSNR: "13.39", LPIPS: "0.33", CLIP: "0.97" },
  baselines: [
    { name: "Gen3DSR", SSIM: "0.76", PSNR: "10.96", LPIPS: "0.34", CLIP: "0.91" },
    { name: "MIDI", SSIM: "0.80", PSNR: "12.85", LPIPS: "0.25", CLIP: "0.92" },
    { name: "SceneGen", SSIM: "0.79", PSNR: "12.25", LPIPS: "0.31", CLIP: "0.96" },
    { name: "TRELLIS", SSIM: "0.80", PSNR: "13.31", LPIPS: "0.31", CLIP: "0.95" },
    { name: "Ours", SSIM: "0.79", PSNR: "13.39", LPIPS: "0.33", CLIP: "0.97" },
  ],
  limitation: "HIVE-3D relies on the initial scene produced by TRELLIS. If objects are missed or incomplete at this stage, correspondence and registration may become unreliable.",
  links: { paper: "./paper/HIVE-3D_final.pdf", code: "Coming Soon", model: "Coming Soon" },
  bibtex: `@inproceedings{zang2026hive3d,
  title     = {HIVE-3D: Hierarchical Voxel Enhancement for High-Quality 3D Scene Generation},
  author    = {Zang, Bin and Zheng, Wenting and Luo, Xiaoliang and Fang, Zhiyuan and Li, Shi and Wang, Lvchun and Yu, Wei and Zhao, Yi and Xie, Tian and Huo, Yuchi and Xie, Rengan},
  booktitle = {Proceedings of the 43rd International Conference on Machine Learning},
  series    = {Proceedings of Machine Learning Research},
  volume    = {306},
  year      = {2026}
}`,
} as const;
